# Generated by Django 5.1.1 on 2024-12-05 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_buyer', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('nama_buyer', models.CharField(max_length=100)),
                ('id_buyer', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pondok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255, null=True)),
                ('universitas', models.CharField(max_length=255, null=True)),
                ('harga_tahun', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('harga_bulan', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('tipe', models.CharField(max_length=50, null=True)),
                ('fasilitas', models.TextField(null=True)),
                ('rating_jaringan', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('rating_kebersihan', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('rating_air', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('jumlah_kamar', models.IntegerField(null=True)),
                ('gambar', models.CharField(max_length=255, null=True)),
                ('alamat', models.TextField(null=True)),
                ('link_alamat', models.URLField(null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('aturan', models.TextField(null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pondok_orders', to='polls.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pondok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_in_pondok', to='polls.pondok'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
