# Generated by Django 5.1.1 on 2024-12-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pondok',
            name='orders',
        ),
    ]
