# Generated by Django 5.1.1 on 2024-12-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_pondok_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondok',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pondok_orders', to='polls.order'),
        ),
    ]
