# Generated by Django 5.1.1 on 2024-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_pondok_harga_pondok_catatan_pondok_gambar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondok',
            name='gambar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pondok',
            name='harga_bulan',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='pondok',
            name='harga_tahun',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='pondok',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='pondok',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
