# Generated by Django 5.1.1 on 2024-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pondok_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staf', 'staf'), ('publik', 'publik')], default='publik', max_length=10),
        ),
    ]
