# Generated by Django 5.1.1 on 2024-12-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondokImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pondok_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pondok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_in_pondok', to='polls.pondok')),
            ],
        ),
        migrations.AlterField(
            model_name='pondok',
            name='gambar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pondok_images', to='polls.pondokimage'),
        ),
    ]
