# Generated by Django 5.1.1 on 2024-12-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_pondokimage_alter_pondok_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pondok',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='pondok',
            name='orders',
        ),
    ]
