# Generated by Django 5.1.1 on 2024-12-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_pondok_gambar_remove_pondok_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pondok',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pondok',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pondok',
            name='link_alamat',
        ),
        migrations.RemoveField(
            model_name='pondok',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pondokimage',
            name='pondok',
        ),
    ]
