# Generated by Django 5.1.1 on 2024-12-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_pondok_alamat_pondok_latitude_pondok_link_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondokimage',
            name='pondok',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images_in_pondok', to='polls.pondok'),
            preserve_default=False,
        ),
    ]
